baseURL: "https://handbook.redesigned-doodle.org"
languageCode: ja-jp
title: Handbook
theme: [PaperMod]
pagination.paperSize: 5

menu:
  main:
    - name: Company
      url: company
      weight: 5

params:
  ShowToc: true

  homeInfoParams:
    Title: "Handbook"
    Content: >
      私たちは開発チーム向けに便利な製品をつくろうとしています。
      製品のビジョンや戦略、内容は公開しています。お好きに見ていってください！

  socialIcons:
    - name: github
      title: GitHub
      url: https://github.com/redesigned-doodle/handbook
    - name: bluesky
      title: bluesky
      url: https://bsky.app/profile/sakanate.bsky.social
    - name: X
      title: X
      url: https://x.com/sakanately