baseURL: "https://handbook.redesigned-doodle.org"
languageCode: ja-jp
defaultContentLanguage: en

title: Handbook
theme: [PaperMod]
enableEmoji: true
pagination.paperSize: 5

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
  ja:
    languageName: "Japanese"
    weight: 2
    params:
      homeInfoParams:
        Title: "Handbook"
        Content: >
          私たちは開発チーム向けに便利な製品をつくろうとしています。
          製品のビジョンや戦略、内容は公開しています。お好きに見ていってください！

params:
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true

  homeInfoParams:
    Title: "Handbook"
    Content: >
      We’re building a useful product for development teams.
      Our vision, strategy, and product details are all publicly available — feel free to take a look!

  socialIcons:
    - name: github
      title: GitHub
      url: https://github.com/redesigned-doodle/handbook
    - name: bluesky
      title: bluesky
      url: https://bsky.app/profile/sakanate.bsky.social
    - name: X
      title: X
      url: https://x.com/sakanately